image: khihdh/group1:pythonimage

stages:
  - Static Analysis
  - test
  - deploy

variables:
  CI_REGISTRY: docker.io
  CI_REGISTRY_IMAGE: index.docker.io/$USERNAME_DOCKER/group1
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

build:
  stage: deploy
  image: docker:19.03.12
  services:
    - name: docker:dind
      entrypoint: ["env", "-u", "DOCKER_HOST"]
      command: ["dockerd-entrypoint.sh"]
      
  before_script:
    - docker login -u "$USERNAME_DOCKER" -p "$PASSWORD_DOCKER" $CI_REGISTRY

  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"


flake8:
  stage: Static Analysis
  script:
    - flake8 --extend-ignore=E501 ./*.py

test:
  stage: test
  script:
    - python -m unittest interfaceAdminTest
coverage:
    stage: test
    before_script:
        - pip install paramiko
        - pip install coverage
    script:
        - coverage run -m unittest interfaceAdminTest
        - coverage report
        - coverage xml
    artifacts:
        reports:
            cobertura: coverage.xml
